version: '3'

services:
  electrum:
    build: .
    ports:
      - 7000:7000
    volumes:
      - electrum_data:/data
    environment:
      ELECTRUM_USER: electrum
      ELECTRUM_PASSWORD: changeme
      WALLET: /data/wallets/mywallet

volumes:
  electrum_data: {}